# Generated by Django 3.0.5 on 2021-05-31 16:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('teacher', '0002_teacher_salary'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='teacher',
            name='salary',
        ),
        migrations.AddField(
            model_name='teacher',
            name='parish_name',
            field=models.CharField(max_length=40, null=True),
        ),
        migrations.AddField(
            model_name='teacher',
            name='province',
            field=models.CharField(max_length=40, null=True),
        ),
    ]
