# Generated by Django 3.0.5 on 2021-05-31 19:04

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('quiz', '0006_auto_20210531_2004'),
    ]

    operations = [
        migrations.AlterField(
            model_name='course',
            name='start_time',
            field=models.DateTimeField(default=datetime.datetime(2021, 5, 31, 20, 4, 19, 804814)),
        ),
    ]
