# Generated by Django 3.0.5 on 2021-06-01 11:00

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('quiz', '0008_auto_20210531_2030'),
    ]

    operations = [
        migrations.AddField(
            model_name='course',
            name='end_time',
            field=models.DateTimeField(default=datetime.datetime(2021, 6, 1, 12, 0, 9, 462283)),
        ),
        migrations.AddField(
            model_name='course',
            name='start_time',
            field=models.DateTimeField(default=datetime.datetime(2021, 6, 1, 12, 0, 9, 462283)),
        ),
    ]
