# Generated by Django 3.0.5 on 2021-05-31 15:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('student', '0002_remove_student_status'),
    ]

    operations = [
        migrations.AddField(
            model_name='student',
            name='parish_name',
            field=models.CharField(max_length=40, null=True),
        ),
        migrations.AddField(
            model_name='student',
            name='province',
            field=models.CharField(max_length=40, null=True),
        ),
    ]
